name: Commit
on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: do-something
jobs:
  main:
    uses: "gracig/actions/.github/workflows/main.yml@main"
    secrets: inherit
    with:
      APP_VERSION: 1.0.0
      ENV_REPO: repo
      DEPLOY_BRANCH: true
      DOTNET_SDK_VERSION: 6.0.x
      DOTNET_SOLUTION_FILE: NG.CS.SampleWebApi.sln
      DOTNET_APP_PATH: ./
      DOTNET_NUGET_SLEET_FEED_NAMES: LibNugetFeed CCRFeed
      CONTAINER_AWS_REPO_NAME: awsrepo
      CONTAINER_AZURE_REPO_NAME: azurerepo
      WORKFLOW_TAGs: |
        dotnet/v2
        container/v1
        argocd-deploy/v2
        debug

      DOTNET_NUGET_STRATEGY: none
      CONTAINER_BUILD_STRATEGY: none
