name: Commit
on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: do-something
jobs:
  main:
    uses: "gracig/actions/.github/workflows/main.yaml@main"
    secrets: inherit
    with:
      WORKFLOW_TAGs: |
        dotnet/v2
        container/v2
        argocd-deploy/v1
        debug
      
      #Mandatory parameters
      APP_VERSION: 1.0.0
      ENV_REPO: repo
      DEPLOY_BRANCH: true

      #Mandatory for dotnet projects
      DOTNET_SOLUTION_FILE: NG.CS.SampleWebApi.sln

      #Optional for dotnet projects
      DOTNET_APP_PATH: ./
      DOTNET_SDK_VERSION: 6.0.x
      DOTNET_NUGET_SLEET_FEED_NAMES: LibNugetFeed CCRFeed
      DOTNET_NUGET_STRATEGY: sleet/v1

      #Mandatory for container projects
      CONTAINER_AWS_REPO_NAME: awsrepo
      CONTAINER_AZURE_REPO_NAME: azurerepo

      #Optional for container projects
      CONTAINER_BUILD_STRATEGY: docker-cli/v1


