name: Commit
on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: do-something
jobs:
  main:
    uses: "gracig/actions/.github/workflows/main.yml@main"
    secrets: inherit
    with:
      APP_VERSION: 1.0.0
      ENV_REPO: repo
      DEPLOY_BRANCH: true
      DOTNET_SOLUTION_FILE: NG.CS.SampleWebApi.sln
      DOTNET_SDK_VERSION: 6.0.x
      WORKFLOW_TAGs: |
        dotnet/v1
        container/v1
        argocd-deploy/v1
        debug
