name: Commit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  main:
    uses: "gracig/actions/.github/workflows/main.yml@main"
    with:
      WORKFLOW_TAGs: |
        dotnet/v1
      DEPLOY_BRANCH: true
      ENV_REPO: repo
      ACR_USERNAME:: ${{ secrets.ACR_USERNAME }}

