name: Commit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: do-something
jobs:
  main:
    uses: "gracig/actions/.github/workflows/main.yml@main"
    with:
      WORKFLOW_TAGs: |
        dotnet/v1
        container/v1
        debug
      DOTNET_SOLUTION_FILE: NG.CS.SampleWebApi.sln
      DOTNET_SDK_VERSION: 6.0.x
      DOTNET_APP_VERSION: 1.0.0:${{ github.sha }}
      DEPLOY_BRANCH: true
      ENV_REPO: repo

    secrets: inherit

